### ISSUE TITLE
how to use without composer

### ISSUE THREAD

**Issue by jandreas0210** [ThauEx/SimpleHtmlDom#7]
Hi

Just wondering how to use this script without composer?
Should I include all 3 file? 

Thank you :)

(sorry noob question, just learn php)

**Comment by rubens-shoji** [comment]
you can use the original project, should work https://sourceforge.net/projects/simplehtmldom/ just include!

**Comment by jandreas0210** [comment]
@rubensfernandes thx for the reply mate :) , actually I already use the original before, after found this, i really love to use it since it have cache system, but dont wanna use composer, just want to include it, just like the original one, is it possible?

thank you :)

**Comment by ThauEx** [comment]
Sure, just require/include all files.

**Comment by jandreas0210** [comment]
ahh really? just simple like that? wow let me try

thx before @ThauEx really appreciate it :)

gonna try it right now :)

**Comment by jandreas0210** [comment]
its work thank you @ThauEx  :) also @rubensfernandes  for the reply :)
